routes/web.php
<?php

/**
 * Route for frontend functionality
 */
Route::get('/', 'Frontend\BlogController@index')->name('index');
Route::get('/blogs/{post}', 'Frontend\BlogController@show')->name('show');
Route::get('/blogs/category/{categorySlug}', 'Frontend\BlogController@category')->name('categories');
Route::get('/blogs/author/{author}', 'Frontend\BlogController@author')->name('authors');
Auth::routes();

/**
 * Route for backend functionality
 */
Route::resource('/backend/blog', Backend\BlogController::class);
Route::resource('/backend/category', Backend\CategoryController::class);
Route::resource('/backend/users', Backend\UserController::class);

Route::name('home')->get('/home', 'Backend\DashboardController@index');
Route::name('blog.restore')->patch('/backend/blog/{blog}/restore', 'Backend\BlogController@restore');
Route::name('blog.delete')->delete('/backend/blog/{blog}/delete', 'Backend\BlogController@delete');
Route::name('users.confirm')->delete('/backend/user/{user}/confirm', 'Backend\UserController@confirm');

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    protected $limitPagination;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->limitPagination = config('cms.pagination.limit');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Post;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\EditPostRequest;
use App\Http\Requests\CreatePostRequest;

class BlogController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $show       = strtolower($request->query('show'));
        $category   = strtolower($request->query('category')) ?? null;

        list($posts, $trashed) = Post::index($show, $category);

        $count = $posts->count();

        if($count > 0){
            $posts = $posts->with('category', 'author')->paginate($this->limitPagination);
        }

        $postsCount = Post::countEveryStatusPosts();

        return view('admin.posts.index')->with('posts', $posts)
                                       ->with('postsCount', $postsCount)
                                       ->with('count', $count)
                                       ->with('trashed', $trashed);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('id', 'title');
        return view('admin.posts.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        if ($request->hasFile('image')) {
            $request->image = Post::uploadImage($request->file('image'));
        }

        Post::publish($request);

        return redirect()->route('blog.index')
                        ->with('success', 'Posts success published');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $blog)
    {
        return $blog;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($blog)
    {
        $blog = Post::withTrashed()->findOrFail($blog);
        $categories = Category::pluck('id', 'title');
        return view('admin.posts.edit')->with('post', $blog)
                                     ->with('categories', $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(EditPostRequest $request, Post $blog)
    {
        $blog->postUpdate($request);
        return redirect()->route('blog.index')->with('success', 'Posts success upadated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $blog)
    {
        $blog->delete();
        return redirect()->back()->with('success', 'Post has been moved to trash')
                                ->with('trashedPost', $blog->id);
    }

    /**
     * Restore the specified resource from storage on trashed
     *
     * @param [type] $blog
     * @return void
     */
    public function restore($blog)
    {
        $blog = Post::onlyTrashed()->findOrFail($blog);
        $blog->restore();
        return redirect()->back()->with('success', 'Post has been restored');
    }

    /**
     * Remove permanently specified resource from storage
     *
     * @param \App\Models\Post $blog
     * @return void
     */
    public function delete($blog)
    {
        $blog = Post::onlyTrashed()->findOrFail($blog);
        $blog->removeImage();
        $blog->forceDelete();

        return redirect()->back()->with('success', 'Post permanently deleted successed');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryCreateRequest;
use App\Http\Requests\CategoryUpdateRequest;

class CategoryController extends BackendController
{

    public function __construct()
    {
        parent::__construct();

        $this->middleware('uncategorized')->only(['edit', 'update', 'delete']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with(['posts' => function($query){
            return $query->withTrashed();
        }])->orderBy('title','asc')->paginate($this->limitPagination);

        $count      = $categories->count();

        foreach($categories as $category) {
            $category->count = $category->posts->count();
        }

        return view('admin.categories.index')->with('categories', $categories)
                                            ->with('count', $count);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryCreateRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('category.index')
                        ->with('success', 'Category Success Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('category.index')
                        ->with('success', 'Category success upadated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $posts = $category->posts()->withTrashed();

        if($posts->count() != 0) {
            $posts->update([
                'category_id' => 6,
            ]);
        }

        $category->delete();
        return redirect()->route('category.index')
                        ->with('success', 'Category success deleted');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Backend\BackendController;

class DashboardController extends BackendController
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.dashboard');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\EditUserRequest;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\DestroyUserRequest;

class UserController extends BackendController
{
    public function __construct()
    {
        parent::__construct();
        $this->middleware('userFilterEdit')->only(['edit', 'update']);
        $this->middleware('userDestroy')->only(['confirm', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate($this->limitPagination);
        $count = $users->count();

        return view('admin.users.index')->with('users', $users)
                                       ->with('count', $count);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $data = User::storeRegisterUser($request);
        User::create($data);

        return redirect()->route('users.index')->with('Users success created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(EditUserRequest $request, User $user)
    {
        $user->updateUserAccount($request);

        return redirect()->route('users.index')->with('success', 'Users has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(DestroyUserRequest $request, User $user)
    {
        $user->deleteUser($request);

        return redirect()->route('users.index')
                        ->with('success', "User {$user->name} success deleted");
    }

    public function confirm(User $user)
    {
        $users      = User::all()->pluck('id', 'name');
        $postCount  = $user->posts()->withTrashed()->count();

        return view('admin.users.confirm-delete')->with('user', $user)
                                                ->with('users', $users)
                                                ->with('postCount', $postCount);
    }
}

resources/views/layouts/backend/partials/errors-message.blade.php
<div class="alert alert-danger">
    <strong>{{ session('errors') }}</strong>
</div>

resources/views/layouts/backend/partials/form-input-create-category.blade.php
<div class="col-xs-9">
  <div class="box">
    <div class="box-body">
      <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
        <label for="title">Title</label>
        <input type="text" class="form-control" name="title" id="title"
        value="{{ $category->title ?? old('title') }}">

        @if($errors->has('title'))
          <span class="help-block">
            <strong>{{ $errors->first('title') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('slug') ? 'has-error' : ''}}">
        <label for="slug">Slug</label>
        <input type="text" class="form-control" name="slug" id="slug" value="{{ $category->slug ?? old('slug') }}">

        @if($errors->has('slug'))
          <span class="help-block">
            <strong>{{ $errors->first('slug') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group">
        <button class="btn btn-primary" type="submit" id="publish">Save</button>
        <a href="{{ route('category.index') }}" class="btn btn-default" id="draft">Cancel</a>
      </div>
    </div>
  </div>
</div>

resources/views/layouts/backend/partials/form-input-create.blade.php
<div class="col-xs-9">
  <div class="box">
    <div class="box-body ">
      @csrf
      <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
        <label for="title">Title</label>
        <input type="text" class="form-control" name="title" id="title" 
        value="{{ old('title') }}">
        
        @if($errors->has('title'))
          <span class="help-block">
            <strong>{{ $errors->first('title') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('slug') ? 'has-error' : ''}}">
        <label for="slug">Slug</label>
        <input type="text" class="form-control" name="slug" id="slug" value="{{ old('slug') }}">

        @if($errors->has('slug'))
          <span class="help-block">
            <strong>{{ $errors->first('slug') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group excerpt {{ $errors->has('excerpt') ? 'has-error' : ''}}">
        <label for="excerpt">Excerpt</label>
        <textarea class="form-control" name="excerpt" id="excerpt">{{ old('excerpt') }}</textarea>

        @if($errors->has('excerpt'))
          <span class="help-block">
            <strong>{{ $errors->first('excerpt') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('body') ? 'has-error' : ''}}">
        <label for="body">Body</label>
        @if($errors->has('body'))
          <span class="help-block">
            <strong>{{ $errors->first('body') }}</strong>
          </span>
        @endif
        <textarea class="form-control {{ $errors->has('body') ? 'has-error' : ''}}" name="body" id="body">{{ old('body') }}</textarea>
      </div>
    </div>
  </div>
</div>

<div class="col-xs-3">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Publish</h3>
    </div>
    <div class="box-body">
      <div class="form-group {{ $errors->has('published_at') ? 'has-error' : ''}}">
        <div class='input-group date' id='datetimepicker'>
          <input type="text" name="published_at" id="publish-date" class="form-control" placeholder="ex : 2018/05/01 09:00:00" value="{{ old('published_at') }}">
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>

        @if($errors->has('published_at'))
          <span class="help-block">
            <strong>{{ $errors->first('published_at') }}</strong>
          </span>
        @endif

      </div>
    </div>
    <div class="box-footer clearfix">
      <div class="pull-left">
        <a href="#" class="btn btn-default" id="draft">Save Draft</a>
      </div>
      <div class="pull-right">
        <div class="form-group">
            <button class="btn btn-primary" type="submit" id="publish">Publish</button>
          </div>
      </div>
    </div>
  </div>
  <div class="box">
    <div class="box-header">
      <h3 class="box-title with-border">Category</h3>
    </div>
    <div class="box-body text-center">
          <div class="form-group {{ $errors->has('category') ? 'has-error' : ''}}">
            <select name="category" class="form-control">
              <option disabled selected hidden>Choose Category</option>
              @foreach($categories as $key => $value)
                <option value="{{ $value }}" {{ old('category') == $value ? 'selected' : '' }}>{{ $key }}</option>
              @endforeach
            </select>

            @if($errors->has('category'))
              <span class="help-block">
                <strong>{{ $errors->first('category') }}</strong>
              </span>
            @endif

          </div>
    </div>
  </div>
  <div class="box">
    <div class="box-header with-border">
      <div class="h3 box-title">Feature Image</div>
    </div>
    <div class="box-body text-center">
      <div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                <img src="{{ asset('storage/img/noimage.png') }}" alt="...">
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
              <div>
                <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input type="file" name="image"></span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
          </div>

            @if($errors->has('image'))
              <span class="help-block">
                <strong>{{ $errors->first('image') }}</strong>
              </span>
            @endif

          </div>
    </div>
  </div>
</div>

resources/views/layouts/backend/partials/form-input-edit.blade.php
<div class="col-xs-9">
  <div class="box">
    <div class="box-body ">
      @csrf
      <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
        <label for="title">Title</label>
        <input type="text" class="form-control" name="title" id="title" 
        value="{{ $post->title }}">
        
        @if($errors->has('title'))
          <span class="help-block">
            <strong>{{ $errors->first('title') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('slug') ? 'has-error' : ''}}">
        <label for="slug">Slug</label>
        <input type="text" class="form-control" name="slug" id="slug" value="{{ $post->slug }}">

        @if($errors->has('slug'))
          <span class="help-block">
            <strong>{{ $errors->first('slug') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group excerpt {{ $errors->has('excerpt') ? 'has-error' : ''}}">
        <label for="excerpt">Excerpt</label>
        <textarea class="form-control" name="excerpt" id="excerpt">{{ $post->excerpt }}</textarea>

        @if($errors->has('excerpt'))
          <span class="help-block">
            <strong>{{ $errors->first('excerpt') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('body') ? 'has-error' : ''}}">
        <label for="body">Body</label>
        @if($errors->has('body'))
          <span class="help-block">
            <strong>{{ $errors->first('body') }}</strong>
          </span>
        @endif
        <textarea class="form-control {{ $errors->has('body') ? 'has-error' : ''}}" name="body" id="body">{{ $post->body }}</textarea>
      </div>
    </div>
  </div>
</div>

<div class="col-xs-3">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Publish</h3>
      <br>
      <span class="label label-{{ $post->status()['class'] }}">{{ $post->status()['status'] }}</span>
    </div>
    @if($post->status()['status'] !== 'published')
    <div class="box-body">
      <div class="form-group {{ $errors->has('published_at') ? 'has-error' : ''}}">
          <div class='input-group date' id='datetimepicker'>
            <input type="text" name="published_at" id="publish-date" class="form-control" placeholder="ex : 2018/05/01 09:00:00" value="{{ $post->published_at ? $post->published_at->format('Y/m/d H:i:s') : '' }}">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        
        @if($errors->has('published_at'))
          <span class="help-block">
            <strong>{{ $errors->first('published_at') }}</strong>
          </span>
        @endif

      </div>
    </div>
    @endif
    <div class="box-footer clearfix">
      <div class="pull-left">
        <a href="#" class="btn btn-default" id="draft">Save Draft</a>
      </div>
      <div class="pull-right">
        <div class="form-group">
            <button class="btn btn-primary" type="submit" id="publish">Publish</button>
          </div>
      </div>
    </div>
  </div>
  <div class="box">
    <div class="box-header">
      <h3 class="box-title with-border">Category</h3>
    </div>
    <div class="box-body text-center">
          <div class="form-group {{ $errors->has('category') ? 'has-error' : ''}}">
            <select name="category" class="form-control">
              <option disabled selected hidden>Choose Category</option>
              @foreach($categories as $key => $value)
                <option value="{{ $value }}" {{ $post->category_id == $value ? 'selected' : '' }}>{{ $key }}</option>
              @endforeach
            </select>

            @if($errors->has('category'))
              <span class="help-block">
                <strong>{{ $errors->first('category') }}</strong>
              </span>
            @endif

          </div>
    </div>
  </div>
  <div class="box">
    <div class="box-header with-border">
      <div class="h3 box-title">Feature Image</div>
    </div>
    <div class="box-body text-center">
      <div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                <img src="{{ $post->imagethumbUrl ? $post->imageThumbUrl : asset('storage/img/noimage.png') }}" alt="...">
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
              <div>
                <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input type="file" name="image"></span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
          </div>

            @if($errors->has('image'))
              <span class="help-block">
                <strong>{{ $errors->first('image') }}</strong>
              </span>
            @endif

          </div>
    </div>
  </div>
</div>

resources/views/layouts/backend/partials/form-script.blade.php
<script type="text/javascript" src="{{ asset('backend/plugins/simple-mde/js/simplemde.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/plugins/datetimepicker/js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/plugins/datetimepicker/js/datetimepicker.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/plugins/jasny-bootstrap/js/jasny-bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/js/custom.js') }}"></script>

resources/views/layouts/backend/partials/form-styling.blade.php
<link rel="stylesheet" type="text/css" href="{{ asset('backend/plugins/simple-mde/css/simplemde.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('backend/plugins/datetimepicker/css/datetimepicker.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('backend/plugins/jasny-bootstrap/css/jasny-bootstrap.min.css') }}">

resources/views/layouts/backend/partials/form-user-create.blade.php
<div class="col-xs-9">
  <div class="box">
    <div class="box-body ">
      @if(session()->has('error'))
            <div class="alert alert-danger">
              {{ session('error') }} : <strong>{{ session('name') }}</strong>
            </div>
      @endif

      @csrf

      <div class="form-group
      {{ $errors->has('name') ? 'has-error' : null ?? session()->has('error') ? 'has-error' : ''}}
      ">
        <label for="name">Name</label>
        <input type="text" class="form-control" name="name" id="name"
        value="{{ old('name') }}">

        @if($errors->has('name') || session()->has('error'))
          <span class="help-block">
            <strong>{{ $errors->first('name') ?: null ?? session('error') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}">

        @if($errors->has('email'))
          <span class="help-block">
            <strong>{{ $errors->first('email') }}</strong>
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" value="{{ old('password') }}">

        @if($errors->has('password'))
          <span class="help-block">
            @if(!(preg_match("/The password confirmation does not match./i", $errors->first('password'))))
              <strong>{{ $errors->first('password') }}</strong>
            @endif
          </span>
        @endif

      </div>

      <div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
        <label for="password_confirmation">Password Confirmation</label>
        <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" value="{{ old('password_confirmation') }}">

        @if($errors->has('password'))
          @if(preg_match("/The password confirmation does not match./i", $errors->first('password')))
          <span class="help-block">
            <strong>{{ $errors->first('password') }}</strong>
          </span>
          @endif
        @endif

      </div>

        <div class="form-group">
            <button class="btn btn-primary" type="submit" id="publish">Create User</button>
            <a href="{{ route("users.index") }}" class="btn btn-default">Cancel</a>
        </div>
    </div>
  </div>
</div>

resources/views/layouts/backend/partials/index-action-menu.blade.php
@foreach($postsCount as $key => $value)
    <a href="?show={{ $key }}" class="">
        @if(request('show') == $key)
        <span class="btn btn-danger btn-xs">{{ ucwords($key) }} ({{ $value }})</span>
        @else
        @if(!request()->has('show'))
            @if($key == 'all')
                <span class="btn btn-danger btn-xs">{{ ucwords($key) }} ({{ $value }})</span>
            @else
                {{ ucwords($key) }} ({{ $value }})
            @endif
        @else
            {{ ucwords($key) }} ({{ $value }})
        @endif
        @endif
    </a> |
@endforeach

resources/views/layouts/backend/partials/success-message.blade.php
<div class="alert alert-warning">
    <strong>{{ session('success') }}</strong>
    @if(session()->has('trashedPost'))
        <form action="{{ route('blog.restore', ['id' => session('trashedPost')]) }}" method="POST" style="display: inline-block">
            @csrf
            @method('PATCH')
            <button class="btn btn-success btn-xs"><i class="fa fa-undo"></i> Undo</button>
        </form>
    @endif
</div>

resources/views/layouts/backend/partials/table-categories.blade.php
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Action</th>
        <th>Title</th>
        <th>View Posts</th>
        <th>Count</th>
        <th>Date</th>
    </tr>
    </thead>

    <tbody>
    @foreach($categories as $category)
        <tr>
            <td style="width: 7%;">
                <a href="{{ route('category.edit', ['id' => $category->id]) }}" class="btn btn-default btn-xs {{ $category->id === 6 ? "disabled" : ''}}">
                <i class="fa fa-edit"></i>
                </a>
                <form action="{{ route('category.destroy', ['id' => $category->id]) }}" method="POST" style="display: inline-block">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-xs" {{ $category->id === 6 ? "disabled" : ''}} onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></button>
                </form>
            </td>
            <td>
                {{ $category->title }}
            </td>
            <td>
                <a href="{{ route('blog.index') }}?show=category&category={{ $category->slug }}">View Posts</a>
            </td>
            <td class="text-center" style="width: 5%">
                <strong>{{ $category->count }}</strong>
            </td>
            <td style="width: 15%"> {{ $category->dateFormat }} </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/layouts/backend/partials/table-posts.blade.php
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Action</th>
        <th>Title</th>
        <th>Author</th>
        <th>Category</th>
        <th>Date</th>
    </tr>
    </thead>

    <tbody>
    @foreach($posts as $post)
        <tr>
        <td style="width: 7%">
            <a href="{{ route('blog.edit', ['id' => $post->id]) }}" class="btn btn-default btn-xs">
            <i class="fa fa-edit"></i>
            </a>
            <form action="{{ route('blog.destroy', ['id' => $post->id]) }}" method="POST" style="display: inline-block">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
            </form>
        </td>
        <td style="width: 40%"> {{ $post->title }}</td>
        <td width="120"> {{ $post->author->name }}</td>
        <td width="130"> {{ $post->category->title }}</td>
        <td width="160">
            {{ $post->dateFormat() }}
            &nbsp;
            <span class="label label-{{ $post->status()['class'] }}">{{ $post->status()['status'] }}</span>
        </td>
        </tr>
    @endforeach
    </tbody>
</table>