routes/web.php
<?php

/**
 * Route for frontend functionality
 */
Route::get('/', 'Frontend\BlogController@index')->name('index');
Route::get('/blogs/{post}', 'Frontend\BlogController@show')->name('show');
Route::get('/blogs/category/{categorySlug}', 'Frontend\BlogController@category')->name('categories');
Route::get('/blogs/author/{author}', 'Frontend\BlogController@author')->name('authors');
Auth::routes();

/**
 * Route for backend functionality
 */
Route::resource('/backend/blog', Backend\BlogController::class);
Route::resource('/backend/category', Backend\CategoryController::class);
Route::resource('/backend/users', Backend\UserController::class);

Route::name('home')->get('/home', 'Backend\DashboardController@index');
Route::name('blog.restore')->patch('/backend/blog/{blog}/restore', 'Backend\BlogController@restore');
Route::name('blog.delete')->delete('/backend/blog/{blog}/delete', 'Backend\BlogController@delete');
Route::name('users.confirm')->delete('/backend/user/{user}/confirm', 'Backend\UserController@confirm');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $fillable = [
        'title', 'slug'
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function getDateFormatAttribute($value)
    {
        return $this->created_at->format('d/m/Y H:i:s');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryCreateRequest;
use App\Http\Requests\CategoryUpdateRequest;

class CategoryController extends BackendController
{

    public function __construct()
    {
        parent::__construct();

        $this->middleware('uncategorized')->only(['edit', 'update', 'delete']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with(['posts' => function($query){
            return $query->withTrashed();
        }])->orderBy('title','asc')->paginate($this->limitPagination);

        $count      = $categories->count();

        foreach($categories as $category) {
            $category->count = $category->posts->count();
        }

        return view('admin.categories.index')->with('categories', $categories)
                                            ->with('count', $count);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryCreateRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('category.index')
                        ->with('success', 'Category Success Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('category.index')
                        ->with('success', 'Category success upadated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $posts = $category->posts()->withTrashed();

        if($posts->count() != 0) {
            $posts->update([
                'category_id' => 6,
            ]);
        }

        $category->delete();
        return redirect()->route('category.index')
                        ->with('success', 'Category success deleted');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.backend.master')

@section('title')
  Create Category | {{ explode(" ", auth()->user()->name)[1] }}
@endsection

@section('content')
  <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Category
      <small>Category</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('category.index') }}">Category</a></li>
        <li class="active">Create Category</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
          <form action="{{ route('category.store') }}" method="POST" id="form-data">
            @csrf
            @include('layouts.backend.partials.form-input-create-category')
          </form>
        </div>
    </section>
@endsection

@section('script')
    <script>
      $('#title').on('input', function(e){
        let title = $(this).val().toLowerCase();
        slug = title.replace(/^&/g, 'and-')
                    .replace(/&/g, '-and-')
                    .replace(/[^0-9a-z-]/g, '-')
                    .replace(/-\-+/g, '-')
                    .replace(/^-+|-+$/g, '');

        $('#slug').val(slug);
      });
    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.backend.master')

@section('title')
  Edit Category | {{ explode(" ", auth()->user()->name)[1] }}
@endsection

@section('content')
  <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Category
      <small>Category</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('category.index') }}">Category</a></li>
        <li class="active">Edit Category</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
          <form action="{{ route('category.update', ['category' => $category->id]) }}" method="POST" id="form-data">
            @csrf
            @method('PATCH')
            @include('layouts.backend.partials.form-input-create-category')
          </form>
        </div>
    </section>
@endsection

@section('script')
    <script>
      $('#title').on('input', function(e){
        let title = $(this).val().toLowerCase();
        slug = title.replace(/^&/g, 'and-')
                    .replace(/&/g, '-and-')
                    .replace(/[^0-9a-z-]/g, '-')
                    .replace(/-\-+/g, '-')
                    .replace(/^-+|-+$/g, '');

        $('#slug').val(slug);
      });
    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.backend.master')

@section('title')
  All Categories | {{ explode(" ", auth()->user()->name)[1] }}
@endsection

@section('content')
  <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Categories
      <small>Display all categories</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('category.index') }}">Categories</a></li>
        <li class="active">All Categories</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <div class="box">
              <div class="box-header">
                <a href="{{ route('category.create') }}" class="btn btn-success">Add New</a>
              </div>
              <div class="box-body ">
                @include('layouts.backend.partials.success-message')
                @if(!$categories->count())
                  <div class="alert alert-danger">
                    <strong>No record found</strong>
                  </div>
                @else
                  @include('layouts.backend.partials.table-categories')
                @endif
              </div>
              <!-- /.box-body -->
              <div class="box-footer clear-fix">
                <div class="pull-left">
                  {{ $categories->links() }}
                </div>
                <div class="pull-right">
                  <small>{{ $count }} {{ str_plural('items', $count ) }}</small>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
@endsection